### ISSUE TITLE
Issue running example with load_model()

### ISSUE THREAD

**Issue by luisArandas** [v-iashin/SpecVQGAN#5]
Hello!

First of all thank you for this amazing work. I'll definitely use it.

The thing is I'm running into an issue when trying to initialize the algorithm. On the fourth cell of your notebook https://colab.research.google.com/drive/1pxTIMweAKApJZ3ZFqyBee3HtMqFpnwQ0?usp=sharing#scrollTo=FeJarWQuFQOT when calling the load_model() I have an error. I'll paste a bit of code here to illustrate:

```
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model_name = '2021-07-30T21-34-25_vggsound_transformer'
log_dir = 'SpecVQGAN/logs'
config, sampler, melgan, melception = load_model(model_name, log_dir, device)
```

The model downloads and I get the warning:

```
device  cuda                                                                                                                    
Using: 2021-07-30T21-34-25_vggsound_transformer (5 ResNet50 Features)
3.68GB [01:55, 31.7MB/s]                                                                                                        
Unpacking SpecVQGAN/logs/2021-07-30T21-34-25_vggsound_transformer.tar.gz to SpecVQGAN/logs
```

But seconds after the unpack I get this error:
```

Traceback (most recent call last):
  File "/home/luis/Desktop/clip/scripts/test_both_libs.py", line 73, in <module>
    config, sampler, melgan, melception = load_model(model_name, log_dir, device)
  File "SpecVQGAN/feature_extraction/demo_utils.py", line 191, in load_model
    config = load_config(model_dir)
  File "SpecVQGAN/feature_extraction/demo_utils.py", line 178, in load_config
    if config.data.params[a] is not None:
  File "/home/luis/anaconda3/envs/pytorch/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 373, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/luis/anaconda3/envs/pytorch/lib/python3.9/site-packages/omegaconf/base.py", line 190, in _format_and_raise
    format_and_raise(
  File "/home/luis/anaconda3/envs/pytorch/lib/python3.9/site-packages/omegaconf/_utils.py", line 821, in format_and_raise
    _raise(ex, cause)
  File "/home/luis/anaconda3/envs/pytorch/lib/python3.9/site-packages/omegaconf/_utils.py", line 719, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set end OC_CAUSE=1 for full backtrace
  File "/home/luis/anaconda3/envs/pytorch/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 367, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/home/luis/anaconda3/envs/pytorch/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 438, in _get_impl
    node = self._get_node(key=key, throw_on_missing_key=True)
  File "/home/luis/anaconda3/envs/pytorch/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 470, in _get_node
    raise ConfigKeyError(f"Missing key {key}")
omegaconf.errors.ConfigKeyError: Missing key flow_feats_dir_path
    full_key: data.params.flow_feats_dir_path
    object_type=dict

```

I can post my `conda list` if needed, pytorch is running CUDA enabled and works fine with other projects (I guess).
Pytorch 1.9.1.post3
NVIDIA RTX3070
CUDA 11.2

Any idea what it might be?
Thanks in advance

**Comment by v-iashin** [comment]
Hi. I think I saw this error before. Can you confirm that your Omegaconf package has another version?

**Comment by luisArandas** [comment]
Hello. Indeed it has. I can try downgrading and check if it solves!

`omegaconf                 2.1.1                    pypi_0    pypi`

**Comment by v-iashin** [comment]
Ok. I also confirmed it myself on Colab just now. Please downgrade it and tell me how it goes.

**Comment by luisArandas** [comment]
Ok just did, got a different text with the `FileNotFoundError`:

```
device  cuda                                                                                                                    
Using: 2021-07-30T21-34-25_vggsound_transformer (5 ResNet50 Features)
3.68GB [02:10, 28.1MB/s]                                                                                                        
Unpacking SpecVQGAN/logs/2021-07-30T21-34-25_vggsound_transformer.tar.gz to SpecVQGAN/logs
Traceback (most recent call last):
  File "/home/luis/Desktop/clip/scripts/test_both_libs.py", line 73, in <module>
    config, sampler, melgan, melception = load_model(model_name, log_dir, device)
  File "SpecVQGAN/feature_extraction/demo_utils.py", line 201, in load_model
    melgan = load_vocoder(ckpt_melgan, eval_mode=True)['model'].to(device)
  File "SpecVQGAN/sample_visualization.py", line 144, in load_vocoder
    vocoder_sd = torch.load(ckpt_vocoder / 'best_netG.pt', map_location='cpu')
  File "/home/luis/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/luis/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/luis/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'vocoder/logs/vggsound/best_netG.pt'
```

Ok might this error related to the fact that I'm not running this inside the SpecVQGAN folder? Relative paths text problem. Just because `vocoder/logs/vggsound/best_netG.pt` is actually there.

**Comment by v-iashin** [comment]
> this error related to the fact that I'm not running this inside the SpecVQGAN folder

💯

**Comment by v-iashin** [comment]
Considering as resolved.
